# Generated by Django 4.2.13 on 2025-09-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
